/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAutopilotRouteImport } from './routes/_app/autopilot'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppChannelsRouteImport } from './routes/_app/channels'
import { Route as AppCreateRouteImport } from './routes/_app/create'
import { Route as AppGrowRouteImport } from './routes/_app/grow'
import { Route as AppMonetizeRouteImport } from './routes/_app/monetize'
import { Route as AppMonitorRouteImport } from './routes/_app/monitor'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutopilotRoute = AppAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowRoute = AppGrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => AppRoute,
} as any)
const AppMonetizeRoute = AppMonetizeRouteImport.update({
  id: '/monetize',
  path: '/monetize',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/autopilot': typeof AppAutopilotRoute
  '/calendar': typeof AppCalendarRoute
  '/channels': typeof AppChannelsRoute
  '/create': typeof AppCreateRoute
  '/grow': typeof AppGrowRoute
  '/monetize': typeof AppMonetizeRoute
  '/monitor': typeof AppMonitorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/autopilot': typeof AppAutopilotRoute
  '/calendar': typeof AppCalendarRoute
  '/channels': typeof AppChannelsRoute
  '/create': typeof AppCreateRoute
  '/grow': typeof AppGrowRoute
  '/monetize': typeof AppMonetizeRoute
  '/monitor': typeof AppMonitorRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/autopilot': typeof AppAutopilotRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/channels': typeof AppChannelsRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/grow': typeof AppGrowRoute
  '/_app/monetize': typeof AppMonetizeRoute
  '/_app/monitor': typeof AppMonitorRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/autopilot'
    | '/calendar'
    | '/channels'
    | '/create'
    | '/grow'
    | '/monetize'
    | '/monitor'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/autopilot'
    | '/calendar'
    | '/channels'
    | '/create'
    | '/grow'
    | '/monetize'
    | '/monitor'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/autopilot'
    | '/_app/calendar'
    | '/_app/channels'
    | '/_app/create'
    | '/_app/grow'
    | '/_app/monetize'
    | '/_app/monitor'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/autopilot': {
      id: '/_app/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AppAutopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grow': {
      id: '/_app/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof AppGrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monetize': {
      id: '/_app/monetize'
      path: '/monetize'
      fullPath: '/monetize'
      preLoaderRoute: typeof AppMonetizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitor': {
      id: '/_app/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAutopilotRoute: typeof AppAutopilotRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppCreateRoute: typeof AppCreateRoute
  AppGrowRoute: typeof AppGrowRoute
  AppMonetizeRoute: typeof AppMonetizeRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutopilotRoute: AppAutopilotRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppCreateRoute: AppCreateRoute,
  AppGrowRoute: AppGrowRoute,
  AppMonetizeRoute: AppMonetizeRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
